title: "Toronto to Tsiigehtchic"
# baseurl: "/" # Use "/" if hosting on root
# url: "http://lkirk121.github.io"
email: "torontototsiigehtchic@gmail.com"
description: "Teaching north of the Arctic Circle... and below the tree line."
